"""Write the pound wallet's rate file: date,CAD,GBP from the ECB history.

    python tools/publish_pound_rates.py

The wallet proper ships docs/app/fx_rates.csv with the columns money.TARGETS
names -- CAD and USD, no GBP. The ECB history zip carries 41 currencies and
GBP is one of them, so this pulls the same file and keeps a different pair.
A separate file rather than a third column on the existing one: adding GBP
to money.TARGETS would change what the published wallet converts, which is
not what was asked for and would restate every figure on its page.

Rows keep whatever legs the ECB published, including days with only one of
the two. Dropping the incomplete ones would quietly shift the business-day
walk-back onto a different date; leaving them in means pounds.cad_per_gbp
sees the two legs land on different days and refuses, which is the outcome
worth having.
"""
import argparse
import csv
import io
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

import fetch      # noqa: E402
import fxrates    # noqa: E402
import pounds     # noqa: E402

OUT = os.path.join(ROOT, "standalone", "pounds")
PAIR = ("CAD", "GBP")

# The cases both implementations have to agree on. Dates chosen for the rules
# they exercise, not for being round: a Sunday and a Saturday for the
# walk-back, a Monday after a bank holiday, and amounts that land on a
# rounding boundary rather than a clean figure.
CASE_DATES = ("2026-09-11", "2026-09-06", "2026-09-07", "2026-01-02",
              "2025-12-26", "2020-03-19", "2015-07-01", "1999-01-04")
CASE_AMOUNTS = (1, 99, 100, 2550, 12345, 100000, 250000)


def build_rows(timeout=120):
    raw = fetch.get(fxrates.HISTORY_URL, timeout)
    if not raw:
        raise SystemExit("could not download the ECB history")
    rates = fxrates._parse_history(raw, wanted=PAIR)
    if not rates:
        raise SystemExit("the ECB history parsed to nothing")
    return rates


def write_csv(rates, path):
    with io.open(path, "w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(["date"] + list(PAIR))
        for on in sorted(rates, reverse=True):
            writer.writerow([on.isoformat()] +
                            [str(rates[on].get(cur, "")) for cur in PAIR])


def write_cases(path, directory):
    """The shared fixture: what Python says, for the browser to be held to.

    Generated from pounds.py, so it is Python's answers by construction --
    the value is entirely in the JS side being checked against it. A case
    whose rate lookup raises is recorded as an error with its message, since
    refusing is as much a rule as converting.
    """
    cases = []
    for on in CASE_DATES:
        try:
            cad_rate, gbp_rate, rate_date = pounds.legs(on, directory=directory)
        except Exception as bad:
            cases.append({"on": on, "error": type(bad).__name__})
            continue
        for cad in CASE_AMOUNTS:
            got = pounds.to_pounds(cad, cad_rate, gbp_rate)
            cases.append({
                "on": on,
                "rateDate": rate_date.isoformat(),
                # Both legs, not the cross rate: the browser has to do the
                # same division from the same integers, so handing it the
                # answer would check nothing.
                "cadRate": str(cad_rate),
                "gbpRate": str(gbp_rate),
                "cross": got["cross"],
                "cadMinor": cad,
                "referenceMinor": got["reference_minor"],
                "poundsMinor": got["pounds_minor"],
                "feeMinor": got["fee_minor"],
                "effectiveRate": got["effective_rate"],
            })

    payload = {
        "note": ("Generated by tools/publish_pound_rates.py. Python's "
                 "answers; tests/test_pounds.py asserts the browser agrees."),
        "limitMinor": pounds.LIMIT_MINOR,
        "feeBp": pounds.CIBC_FEE_BP,
        "cases": cases,
    }
    with io.open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(json.dumps(payload, indent=2) + "\n")
    return len(cases)


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--timeout", type=int, default=120)
    args = parser.parse_args()

    os.makedirs(OUT, exist_ok=True)
    rates = build_rows(args.timeout)

    csv_path = os.path.join(OUT, "fx_rates.csv")
    write_csv(rates, csv_path)

    both = sum(1 for day in rates.values() if len(day) == len(PAIR))
    print("  %s" % csv_path)
    print("  %s days, %s to %s, %s with both legs"
          % (len(rates), min(rates).isoformat(), max(rates).isoformat(), both))

    fxrates.reset()
    count = write_cases(os.path.join(OUT, "cases.json"), OUT)
    print("  cases.json: %s cases" % count)


if __name__ == "__main__":
    main()
